// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: control.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LPS.Server.Core.Rpc.InnerMessages {

  /// <summary>Holder for reflection information generated from control.proto</summary>
  public static partial class ControlReflection {

    #region Descriptor
    /// <summary>File descriptor for control.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ControlReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1jb250cm9sLnByb3RvEiFMUFMuU2VydmVyLkNvcmUuUnBjLklubmVyTWVz",
            "c2FnZXMaGWdvb2dsZS9wcm90b2J1Zi9hbnkucHJvdG8irgEKB0NvbnRyb2wS",
            "OwoERnJvbRgBIAEoDjItLkxQUy5TZXJ2ZXIuQ29yZS5ScGMuSW5uZXJNZXNz",
            "YWdlcy5SZW1vdGVUeXBlEkIKB01lc3NhZ2UYAiABKA4yMS5MUFMuU2VydmVy",
            "LkNvcmUuUnBjLklubmVyTWVzc2FnZXMuQ29udHJvbE1lc3NhZ2USIgoEQXJn",
            "cxgDIAMoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkqNgoOQ29udHJvbE1lc3Nh",
            "Z2USCQoFUmVhZHkQABILCgdSZXN0YXJ0EAESDAoIU2h1dERvd24QAioxCgpS",
            "ZW1vdGVUeXBlEg0KCURCTWFuYWdlchAAEgoKBlNlcnZlchABEggKBEdhdGUQ",
            "AmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage), typeof(global::LPS.Server.Core.Rpc.InnerMessages.RemoteType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LPS.Server.Core.Rpc.InnerMessages.Control), global::LPS.Server.Core.Rpc.InnerMessages.Control.Parser, new[]{ "From", "Message", "Args" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ControlMessage {
    [pbr::OriginalName("Ready")] Ready = 0,
    [pbr::OriginalName("Restart")] Restart = 1,
    [pbr::OriginalName("ShutDown")] ShutDown = 2,
  }

  public enum RemoteType {
    [pbr::OriginalName("DBManager")] Dbmanager = 0,
    [pbr::OriginalName("Server")] Server = 1,
    [pbr::OriginalName("Gate")] Gate = 2,
  }

  #endregion

  #region Messages
  public sealed partial class Control : pb::IMessage<Control>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Control> _parser = new pb::MessageParser<Control>(() => new Control());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Control> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LPS.Server.Core.Rpc.InnerMessages.ControlReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Control() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Control(Control other) : this() {
      from_ = other.from_;
      message_ = other.message_;
      args_ = other.args_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Control Clone() {
      return new Control(this);
    }

    /// <summary>Field number for the "From" field.</summary>
    public const int FromFieldNumber = 1;
    private global::LPS.Server.Core.Rpc.InnerMessages.RemoteType from_ = global::LPS.Server.Core.Rpc.InnerMessages.RemoteType.Dbmanager;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Server.Core.Rpc.InnerMessages.RemoteType From {
      get { return from_; }
      set {
        from_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage message_ = global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage.Ready;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    /// <summary>Field number for the "Args" field.</summary>
    public const int ArgsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Any> _repeated_args_codec
        = pb::FieldCodec.ForMessage(26, global::Google.Protobuf.WellKnownTypes.Any.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> args_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> Args {
      get { return args_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Control);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Control other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (From != other.From) return false;
      if (Message != other.Message) return false;
      if(!args_.Equals(other.args_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (From != global::LPS.Server.Core.Rpc.InnerMessages.RemoteType.Dbmanager) hash ^= From.GetHashCode();
      if (Message != global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage.Ready) hash ^= Message.GetHashCode();
      hash ^= args_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (From != global::LPS.Server.Core.Rpc.InnerMessages.RemoteType.Dbmanager) {
        output.WriteRawTag(8);
        output.WriteEnum((int) From);
      }
      if (Message != global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage.Ready) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Message);
      }
      args_.WriteTo(output, _repeated_args_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (From != global::LPS.Server.Core.Rpc.InnerMessages.RemoteType.Dbmanager) {
        output.WriteRawTag(8);
        output.WriteEnum((int) From);
      }
      if (Message != global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage.Ready) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Message);
      }
      args_.WriteTo(ref output, _repeated_args_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (From != global::LPS.Server.Core.Rpc.InnerMessages.RemoteType.Dbmanager) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) From);
      }
      if (Message != global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage.Ready) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Message);
      }
      size += args_.CalculateSize(_repeated_args_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Control other) {
      if (other == null) {
        return;
      }
      if (other.From != global::LPS.Server.Core.Rpc.InnerMessages.RemoteType.Dbmanager) {
        From = other.From;
      }
      if (other.Message != global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage.Ready) {
        Message = other.Message;
      }
      args_.Add(other.args_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            From = (global::LPS.Server.Core.Rpc.InnerMessages.RemoteType) input.ReadEnum();
            break;
          }
          case 16: {
            Message = (global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage) input.ReadEnum();
            break;
          }
          case 26: {
            args_.AddEntriesFrom(input, _repeated_args_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            From = (global::LPS.Server.Core.Rpc.InnerMessages.RemoteType) input.ReadEnum();
            break;
          }
          case 16: {
            Message = (global::LPS.Server.Core.Rpc.InnerMessages.ControlMessage) input.ReadEnum();
            break;
          }
          case 26: {
            args_.AddEntriesFrom(ref input, _repeated_args_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
