// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shadow_entity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LPS.Server.Rpc.InnerMessages {

  /// <summary>Holder for reflection information generated from shadow_entity.proto</summary>
  public static partial class ShadowEntityReflection {

    #region Descriptor
    /// <summary>File descriptor for shadow_entity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShadowEntityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzaGFkb3dfZW50aXR5LnByb3RvEhxMUFMuU2VydmVyLlJwYy5Jbm5lck1l",
            "c3NhZ2VzGg1tYWlsYm94LnByb3RvIpwBChlSZXF1aXJlQ3JlYXRlU2hhZG93",
            "RW50aXR5EjkKCk9yaU1haWxCb3gYASABKAsyJS5MUFMuQ29tbW9uLlJwYy5J",
            "bm5lck1lc3NhZ2VzLk1haWxCb3gSGAoQVGFyZ2V0U2VydmVyTmFtZRgCIAEo",
            "CRIXCg9FbnRpdHlDbGFzc05hbWUYAyABKAkSEQoJUmVxdWVzdElkGAQgASgN",
            "IqYBChJDcmVhdGVTaGFkb3dFbnRpdHkSOQoKT3JpTWFpbEJveBgBIAEoCzIl",
            "LkxQUy5Db21tb24uUnBjLklubmVyTWVzc2FnZXMuTWFpbEJveBI8Cg1TaGFk",
            "b3dNYWlsQm94GAIgASgLMiUuTFBTLkNvbW1vbi5ScGMuSW5uZXJNZXNzYWdl",
            "cy5NYWlsQm94EhcKD0VudGl0eUNsYXNzTmFtZRgDIAEoCSLFAQocUmVxdWly",
            "ZUNyZWF0ZVNoYWRvd0VudGl0eVJlcxI5CgpPcmlNYWlsQm94GAEgASgLMiUu",
            "TFBTLkNvbW1vbi5ScGMuSW5uZXJNZXNzYWdlcy5NYWlsQm94EjwKDVNoYWRv",
            "d01haWxCb3gYAiABKAsyJS5MUFMuQ29tbW9uLlJwYy5Jbm5lck1lc3NhZ2Vz",
            "Lk1haWxCb3gSEQoJUmVxdWVzdElkGAMgASgNEgoKAk9rGAQgASgIEg0KBUVy",
            "cm9yGAUgASgJIpUBChpSZXF1aXJlRGVzdHJveVNoYWRvd0VudGl0eRI5CgpP",
            "cmlNYWlsQm94GAEgASgLMiUuTFBTLkNvbW1vbi5ScGMuSW5uZXJNZXNzYWdl",
            "cy5NYWlsQm94EjwKDVNoYWRvd01haWxCb3gYAiABKAsyJS5MUFMuQ29tbW9u",
            "LlJwYy5Jbm5lck1lc3NhZ2VzLk1haWxCb3giUwoTRGVzdHJveVNoYWRvd0Vu",
            "dGl0eRI8Cg1TaGFkb3dNYWlsQm94GAEgASgLMiUuTFBTLkNvbW1vbi5ScGMu",
            "SW5uZXJNZXNzYWdlcy5NYWlsQm94YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LPS.Common.Rpc.InnerMessages.MailboxReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LPS.Server.Rpc.InnerMessages.RequireCreateShadowEntity), global::LPS.Server.Rpc.InnerMessages.RequireCreateShadowEntity.Parser, new[]{ "OriMailBox", "TargetServerName", "EntityClassName", "RequestId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LPS.Server.Rpc.InnerMessages.CreateShadowEntity), global::LPS.Server.Rpc.InnerMessages.CreateShadowEntity.Parser, new[]{ "OriMailBox", "ShadowMailBox", "EntityClassName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LPS.Server.Rpc.InnerMessages.RequireCreateShadowEntityRes), global::LPS.Server.Rpc.InnerMessages.RequireCreateShadowEntityRes.Parser, new[]{ "OriMailBox", "ShadowMailBox", "RequestId", "Ok", "Error" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LPS.Server.Rpc.InnerMessages.RequireDestroyShadowEntity), global::LPS.Server.Rpc.InnerMessages.RequireDestroyShadowEntity.Parser, new[]{ "OriMailBox", "ShadowMailBox" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LPS.Server.Rpc.InnerMessages.DestroyShadowEntity), global::LPS.Server.Rpc.InnerMessages.DestroyShadowEntity.Parser, new[]{ "ShadowMailBox" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// ori-server -> Gate. Request creation of a shadow on a specific server.
  /// Carries request_id so ori-server's CreateShadowEntity API
  /// (which returns Task&lt;MailBox>) can correlate the eventual Res back via
  /// AsyncTaskGenerator&lt;MailBox>.
  /// </summary>
  public sealed partial class RequireCreateShadowEntity : pb::IMessage<RequireCreateShadowEntity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequireCreateShadowEntity> _parser = new pb::MessageParser<RequireCreateShadowEntity>(() => new RequireCreateShadowEntity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequireCreateShadowEntity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LPS.Server.Rpc.InnerMessages.ShadowEntityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireCreateShadowEntity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireCreateShadowEntity(RequireCreateShadowEntity other) : this() {
      oriMailBox_ = other.oriMailBox_ != null ? other.oriMailBox_.Clone() : null;
      targetServerName_ = other.targetServerName_;
      entityClassName_ = other.entityClassName_;
      requestId_ = other.requestId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireCreateShadowEntity Clone() {
      return new RequireCreateShadowEntity(this);
    }

    /// <summary>Field number for the "OriMailBox" field.</summary>
    public const int OriMailBoxFieldNumber = 1;
    private global::LPS.Common.Rpc.InnerMessages.MailBox oriMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox OriMailBox {
      get { return oriMailBox_; }
      set {
        oriMailBox_ = value;
      }
    }

    /// <summary>Field number for the "TargetServerName" field.</summary>
    public const int TargetServerNameFieldNumber = 2;
    private string targetServerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetServerName {
      get { return targetServerName_; }
      set {
        targetServerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EntityClassName" field.</summary>
    public const int EntityClassNameFieldNumber = 3;
    private string entityClassName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityClassName {
      get { return entityClassName_; }
      set {
        entityClassName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RequestId" field.</summary>
    public const int RequestIdFieldNumber = 4;
    private uint requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequireCreateShadowEntity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequireCreateShadowEntity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OriMailBox, other.OriMailBox)) return false;
      if (TargetServerName != other.TargetServerName) return false;
      if (EntityClassName != other.EntityClassName) return false;
      if (RequestId != other.RequestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (oriMailBox_ != null) hash ^= OriMailBox.GetHashCode();
      if (TargetServerName.Length != 0) hash ^= TargetServerName.GetHashCode();
      if (EntityClassName.Length != 0) hash ^= EntityClassName.GetHashCode();
      if (RequestId != 0) hash ^= RequestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (TargetServerName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetServerName);
      }
      if (EntityClassName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EntityClassName);
      }
      if (RequestId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (TargetServerName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetServerName);
      }
      if (EntityClassName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EntityClassName);
      }
      if (RequestId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (oriMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OriMailBox);
      }
      if (TargetServerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetServerName);
      }
      if (EntityClassName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityClassName);
      }
      if (RequestId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RequestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequireCreateShadowEntity other) {
      if (other == null) {
        return;
      }
      if (other.oriMailBox_ != null) {
        if (oriMailBox_ == null) {
          OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        OriMailBox.MergeFrom(other.OriMailBox);
      }
      if (other.TargetServerName.Length != 0) {
        TargetServerName = other.TargetServerName;
      }
      if (other.EntityClassName.Length != 0) {
        EntityClassName = other.EntityClassName;
      }
      if (other.RequestId != 0) {
        RequestId = other.RequestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            TargetServerName = input.ReadString();
            break;
          }
          case 26: {
            EntityClassName = input.ReadString();
            break;
          }
          case 32: {
            RequestId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            TargetServerName = input.ReadString();
            break;
          }
          case 26: {
            EntityClassName = input.ReadString();
            break;
          }
          case 32: {
            RequestId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Gate -> target shadow-server. Tells target to instantiate a shadow.
  /// shadow_mailbox is pre-computed by Gate using the derived-Id scheme
  /// (oriId + "@shadow@" + target_server_name).
  /// </summary>
  public sealed partial class CreateShadowEntity : pb::IMessage<CreateShadowEntity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateShadowEntity> _parser = new pb::MessageParser<CreateShadowEntity>(() => new CreateShadowEntity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateShadowEntity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LPS.Server.Rpc.InnerMessages.ShadowEntityReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateShadowEntity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateShadowEntity(CreateShadowEntity other) : this() {
      oriMailBox_ = other.oriMailBox_ != null ? other.oriMailBox_.Clone() : null;
      shadowMailBox_ = other.shadowMailBox_ != null ? other.shadowMailBox_.Clone() : null;
      entityClassName_ = other.entityClassName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateShadowEntity Clone() {
      return new CreateShadowEntity(this);
    }

    /// <summary>Field number for the "OriMailBox" field.</summary>
    public const int OriMailBoxFieldNumber = 1;
    private global::LPS.Common.Rpc.InnerMessages.MailBox oriMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox OriMailBox {
      get { return oriMailBox_; }
      set {
        oriMailBox_ = value;
      }
    }

    /// <summary>Field number for the "ShadowMailBox" field.</summary>
    public const int ShadowMailBoxFieldNumber = 2;
    private global::LPS.Common.Rpc.InnerMessages.MailBox shadowMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox ShadowMailBox {
      get { return shadowMailBox_; }
      set {
        shadowMailBox_ = value;
      }
    }

    /// <summary>Field number for the "EntityClassName" field.</summary>
    public const int EntityClassNameFieldNumber = 3;
    private string entityClassName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityClassName {
      get { return entityClassName_; }
      set {
        entityClassName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateShadowEntity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateShadowEntity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OriMailBox, other.OriMailBox)) return false;
      if (!object.Equals(ShadowMailBox, other.ShadowMailBox)) return false;
      if (EntityClassName != other.EntityClassName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (oriMailBox_ != null) hash ^= OriMailBox.GetHashCode();
      if (shadowMailBox_ != null) hash ^= ShadowMailBox.GetHashCode();
      if (EntityClassName.Length != 0) hash ^= EntityClassName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShadowMailBox);
      }
      if (EntityClassName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EntityClassName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShadowMailBox);
      }
      if (EntityClassName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EntityClassName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (oriMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShadowMailBox);
      }
      if (EntityClassName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityClassName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateShadowEntity other) {
      if (other == null) {
        return;
      }
      if (other.oriMailBox_ != null) {
        if (oriMailBox_ == null) {
          OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        OriMailBox.MergeFrom(other.OriMailBox);
      }
      if (other.shadowMailBox_ != null) {
        if (shadowMailBox_ == null) {
          ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        ShadowMailBox.MergeFrom(other.ShadowMailBox);
      }
      if (other.EntityClassName.Length != 0) {
        EntityClassName = other.EntityClassName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
          case 26: {
            EntityClassName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
          case 26: {
            EntityClassName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// target shadow-server -> Gate -> ori-server. Confirms construction.
  /// On ok=true, ori-server resolves the awaiting AsyncTaskGenerator and
  /// then emits a PropertyFullSync so the shadow gets seed state.
  /// </summary>
  public sealed partial class RequireCreateShadowEntityRes : pb::IMessage<RequireCreateShadowEntityRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequireCreateShadowEntityRes> _parser = new pb::MessageParser<RequireCreateShadowEntityRes>(() => new RequireCreateShadowEntityRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequireCreateShadowEntityRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LPS.Server.Rpc.InnerMessages.ShadowEntityReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireCreateShadowEntityRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireCreateShadowEntityRes(RequireCreateShadowEntityRes other) : this() {
      oriMailBox_ = other.oriMailBox_ != null ? other.oriMailBox_.Clone() : null;
      shadowMailBox_ = other.shadowMailBox_ != null ? other.shadowMailBox_.Clone() : null;
      requestId_ = other.requestId_;
      ok_ = other.ok_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireCreateShadowEntityRes Clone() {
      return new RequireCreateShadowEntityRes(this);
    }

    /// <summary>Field number for the "OriMailBox" field.</summary>
    public const int OriMailBoxFieldNumber = 1;
    private global::LPS.Common.Rpc.InnerMessages.MailBox oriMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox OriMailBox {
      get { return oriMailBox_; }
      set {
        oriMailBox_ = value;
      }
    }

    /// <summary>Field number for the "ShadowMailBox" field.</summary>
    public const int ShadowMailBoxFieldNumber = 2;
    private global::LPS.Common.Rpc.InnerMessages.MailBox shadowMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox ShadowMailBox {
      get { return shadowMailBox_; }
      set {
        shadowMailBox_ = value;
      }
    }

    /// <summary>Field number for the "RequestId" field.</summary>
    public const int RequestIdFieldNumber = 3;
    private uint requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "Ok" field.</summary>
    public const int OkFieldNumber = 4;
    private bool ok_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Ok {
      get { return ok_; }
      set {
        ok_ = value;
      }
    }

    /// <summary>Field number for the "Error" field.</summary>
    public const int ErrorFieldNumber = 5;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequireCreateShadowEntityRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequireCreateShadowEntityRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OriMailBox, other.OriMailBox)) return false;
      if (!object.Equals(ShadowMailBox, other.ShadowMailBox)) return false;
      if (RequestId != other.RequestId) return false;
      if (Ok != other.Ok) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (oriMailBox_ != null) hash ^= OriMailBox.GetHashCode();
      if (shadowMailBox_ != null) hash ^= ShadowMailBox.GetHashCode();
      if (RequestId != 0) hash ^= RequestId.GetHashCode();
      if (Ok != false) hash ^= Ok.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShadowMailBox);
      }
      if (RequestId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RequestId);
      }
      if (Ok != false) {
        output.WriteRawTag(32);
        output.WriteBool(Ok);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShadowMailBox);
      }
      if (RequestId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RequestId);
      }
      if (Ok != false) {
        output.WriteRawTag(32);
        output.WriteBool(Ok);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (oriMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShadowMailBox);
      }
      if (RequestId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RequestId);
      }
      if (Ok != false) {
        size += 1 + 1;
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequireCreateShadowEntityRes other) {
      if (other == null) {
        return;
      }
      if (other.oriMailBox_ != null) {
        if (oriMailBox_ == null) {
          OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        OriMailBox.MergeFrom(other.OriMailBox);
      }
      if (other.shadowMailBox_ != null) {
        if (shadowMailBox_ == null) {
          ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        ShadowMailBox.MergeFrom(other.ShadowMailBox);
      }
      if (other.RequestId != 0) {
        RequestId = other.RequestId;
      }
      if (other.Ok != false) {
        Ok = other.Ok;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
          case 24: {
            RequestId = input.ReadUInt32();
            break;
          }
          case 32: {
            Ok = input.ReadBool();
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
          case 24: {
            RequestId = input.ReadUInt32();
            break;
          }
          case 32: {
            Ok = input.ReadBool();
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ori-server -> Gate. Per-target destroy request (carries shadow_mailbox
  /// so Gate can prune exactly one subscription entry).
  /// </summary>
  public sealed partial class RequireDestroyShadowEntity : pb::IMessage<RequireDestroyShadowEntity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequireDestroyShadowEntity> _parser = new pb::MessageParser<RequireDestroyShadowEntity>(() => new RequireDestroyShadowEntity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequireDestroyShadowEntity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LPS.Server.Rpc.InnerMessages.ShadowEntityReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireDestroyShadowEntity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireDestroyShadowEntity(RequireDestroyShadowEntity other) : this() {
      oriMailBox_ = other.oriMailBox_ != null ? other.oriMailBox_.Clone() : null;
      shadowMailBox_ = other.shadowMailBox_ != null ? other.shadowMailBox_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequireDestroyShadowEntity Clone() {
      return new RequireDestroyShadowEntity(this);
    }

    /// <summary>Field number for the "OriMailBox" field.</summary>
    public const int OriMailBoxFieldNumber = 1;
    private global::LPS.Common.Rpc.InnerMessages.MailBox oriMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox OriMailBox {
      get { return oriMailBox_; }
      set {
        oriMailBox_ = value;
      }
    }

    /// <summary>Field number for the "ShadowMailBox" field.</summary>
    public const int ShadowMailBoxFieldNumber = 2;
    private global::LPS.Common.Rpc.InnerMessages.MailBox shadowMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox ShadowMailBox {
      get { return shadowMailBox_; }
      set {
        shadowMailBox_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequireDestroyShadowEntity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequireDestroyShadowEntity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OriMailBox, other.OriMailBox)) return false;
      if (!object.Equals(ShadowMailBox, other.ShadowMailBox)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (oriMailBox_ != null) hash ^= OriMailBox.GetHashCode();
      if (shadowMailBox_ != null) hash ^= ShadowMailBox.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShadowMailBox);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (oriMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ShadowMailBox);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (oriMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OriMailBox);
      }
      if (shadowMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShadowMailBox);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequireDestroyShadowEntity other) {
      if (other == null) {
        return;
      }
      if (other.oriMailBox_ != null) {
        if (oriMailBox_ == null) {
          OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        OriMailBox.MergeFrom(other.OriMailBox);
      }
      if (other.shadowMailBox_ != null) {
        if (shadowMailBox_ == null) {
          ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        ShadowMailBox.MergeFrom(other.ShadowMailBox);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (oriMailBox_ == null) {
              OriMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(OriMailBox);
            break;
          }
          case 18: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Gate -> target shadow-server. Tells target to destroy its local shadow.
  /// </summary>
  public sealed partial class DestroyShadowEntity : pb::IMessage<DestroyShadowEntity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DestroyShadowEntity> _parser = new pb::MessageParser<DestroyShadowEntity>(() => new DestroyShadowEntity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DestroyShadowEntity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LPS.Server.Rpc.InnerMessages.ShadowEntityReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DestroyShadowEntity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DestroyShadowEntity(DestroyShadowEntity other) : this() {
      shadowMailBox_ = other.shadowMailBox_ != null ? other.shadowMailBox_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DestroyShadowEntity Clone() {
      return new DestroyShadowEntity(this);
    }

    /// <summary>Field number for the "ShadowMailBox" field.</summary>
    public const int ShadowMailBoxFieldNumber = 1;
    private global::LPS.Common.Rpc.InnerMessages.MailBox shadowMailBox_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LPS.Common.Rpc.InnerMessages.MailBox ShadowMailBox {
      get { return shadowMailBox_; }
      set {
        shadowMailBox_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DestroyShadowEntity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DestroyShadowEntity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ShadowMailBox, other.ShadowMailBox)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (shadowMailBox_ != null) hash ^= ShadowMailBox.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (shadowMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ShadowMailBox);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (shadowMailBox_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ShadowMailBox);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (shadowMailBox_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShadowMailBox);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DestroyShadowEntity other) {
      if (other == null) {
        return;
      }
      if (other.shadowMailBox_ != null) {
        if (shadowMailBox_ == null) {
          ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
        }
        ShadowMailBox.MergeFrom(other.ShadowMailBox);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (shadowMailBox_ == null) {
              ShadowMailBox = new global::LPS.Common.Rpc.InnerMessages.MailBox();
            }
            input.ReadMessage(ShadowMailBox);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
