using System;
using System.Threading.Tasks;
using LPS.Core.Database.GlobalCache;
using LPS.Core.Debug;

namespace LPS.Core.Database
{

    public static class DbHelper
    {
        private static IGlobalCache? fastGlobalCache_;
        // Fast* client allows current process directly access to cache (redis).
        // Be careful to use this api.
        // This api should only be used under latency-sensitive circumstance.
        public static IGlobalCache FastGlobalCache => fastGlobalCache_!;
        // Slow* client posts the access operation message to remote DbManager process.
        // DbManager process holds a message queue to control the cache-access frequency.
        // User should use this api in most cases.
        public static readonly IGlobalCache SlowGlobalCache = new MqGlobalCacheAccessor();

        public static IDatabase FastDatabase => throw new NotImplementedException();
        public static IDatabase SlowDatabase => throw new NotImplementedException();

        public async static Task Initialize()
        {
            Logger.Info("Start initialize database...");
            fastGlobalCache_ = Redis.Instance;
            await fastGlobalCache_.Initialize();
            // todo: slow.initialzie()
            Logger.Info("Initialize database success.");
        }

        public static async Task<string> GenerateNewGlobalId()
        {
            var key = "$_lps_sys_entity_id_counter";
            var numId = await FastGlobalCache.Incr(key);
            return BuildGlobalId(numId);
        }

        private static string BuildGlobalId(long longId)
        {
            // LPS simply use global cache to generate temp entity global id
            // the global id is generated by rule as follow:
            // 1. incr global counter in global cache
            // 2. get global counter's val
            // 3. val % 10e16 (get the last 16 digits)
            // 4. convert val to string and padding to 16-digits string
            // 5. convert 16-digits string to base64 string as the globalid
            var globalID = longId;
            var stringID = Convert.ToString(globalID % 10e16).PadLeft(16, '0');
            var newID = Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(stringID));
            return newID;
        }
    }
}